version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: vshare_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vshare_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - vshare_data:/var/lib/mysql

volumes:
  vshare_data: