name: CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: vshare-app
          path: target/*.jar

  deploy:
    needs: build_and_test # This job depends on the 'build_and_test' job
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: vshare-app
          path: ./app-artifact

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./app-artifact/*.jar"
          target: "~/app"
          strip_components: 1

      - name: Run App on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Kill the old process if it exists
            fuser -k 8080/tcp || true
            # Run the new JAR in the background with DB secrets
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USER=${{ secrets.DB_USER }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            
            # --- BỔ SUNG BIẾN AWS S3 TẠI ĐÂY ---
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
            export AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}
            export AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
            
            nohup java -jar ~/app/*.jar > app.log 2>&1 &
            
            sleep 3
            echo "Checking if app.log exists..."
            ls -l app.log
            echo "First 10 lines of app.log:"
            head -n 10 app.log